"""indexed foreign key columns

Revision ID: 242c0a4918e1
Revises: 84eca7b02baa
Create Date: 2026-01-24 16:18:47.344280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242c0a4918e1'
down_revision: Union[str, Sequence[str], None] = '84eca7b02baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'is_delete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_delete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'suspended_at')
    op.drop_column('users', 'is_suspended')
    # ### end Alembic commands ###
