"""changed is_suspended constraint

Revision ID: 66eeed255933
Revises: 242c0a4918e1
Create Date: 2026-01-24 16:24:11.471656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66eeed255933'
down_revision: Union[str, Sequence[str], None] = '242c0a4918e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_delete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_delete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
