"""changed primary key from comments table to id column

Revision ID: 6ec3ddac96be
Revises: b20e38a407e1
Create Date: 2026-01-25 15:17:41.528488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec3ddac96be'
down_revision: Union[str, Sequence[str], None] = 'b20e38a407e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_pkey'), 'comments', type_='primary')
    op.create_primary_key(op.f('comments_pkey'), 'comments', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key(op.f('comments_pkey'), 'comments', ['post_id', 'user_id'])
    op.drop_constraint(op.f('comments_pkey'), 'comments', type_='primary')
    # ### end Alembic commands ###
