"""changed comments table

Revision ID: b20e38a407e1
Revises: 1e0c8d6ca29c
Create Date: 2026-01-25 14:29:49.837626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20e38a407e1'
down_revision: Union[str, Sequence[str], None] = '1e0c8d6ca29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'likes')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
