"""removed unique constraint from images.image_url

Revision ID: b7ec50088f72
Revises: c6e5f3a78323
Create Date: 2026-01-12 10:21:11.036765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ec50088f72'
down_revision: Union[str, Sequence[str], None] = 'c6e5f3a78323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('images_image_url_key'), 'images', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('images_image_url_key'), 'images', ['image_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
