"""indexed username and display name fields in users table

Revision ID: bbed1e384a35
Revises: b7ec50088f72
Create Date: 2026-01-18 22:04:51.949923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbed1e384a35'
down_revision: Union[str, Sequence[str], None] = 'b7ec50088f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('images_image_url_key'), 'images', type_='unique')
    op.create_index('idx_display_name', 'users', ['display_name'], unique=False, postgresql_using='gin', postgresql_ops={'display_name': 'gin_trgm_ops'})
    op.create_index('idx_username', 'users', ['username'], unique=False, postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_username', table_name='users', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.drop_index('idx_display_name', table_name='users', postgresql_using='gin', postgresql_ops={'display_name': 'gin_trgm_ops'})
    op.create_unique_constraint(op.f('images_image_url_key'), 'images', ['image_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
