"""updated table relationships and created new images table

Revision ID: cb525e2dee5f
Revises: cd2d6032c5a3
Create Date: 2026-01-11 04:20:36.751954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb525e2dee5f'
down_revision: Union[str, Sequence[str], None] = 'cd2d6032c5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    op.add_column('comments', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('post_images', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('post_images', sa.Column('image_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('post_images_user_id_fkey'), 'post_images', type_='foreignkey')
    op.create_foreign_key(None, 'post_images', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post_images', 'created_at')
    op.drop_column('post_images', 'image_url')
    op.drop_column('post_images', 'user_id')
    op.add_column('profile_images', sa.Column('image_id', sa.UUID(), nullable=False))
    op.alter_column('profile_images', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'profile_images', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_column('profile_images', 'created_at')
    op.drop_column('profile_images', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_images', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('profile_images', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'profile_images', type_='foreignkey')
    op.alter_column('profile_images', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('profile_images', 'image_id')
    op.add_column('post_images', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('post_images', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('post_images', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_images', type_='foreignkey')
    op.create_foreign_key(op.f('post_images_user_id_fkey'), 'post_images', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post_images', 'image_id')
    op.drop_column('post_images', 'id')
    op.drop_column('comments', 'id')
    op.drop_table('images')
    # ### end Alembic commands ###
