"""added likes attribute to Comment class

Revision ID: ed28f44c90ec
Revises: bbed1e384a35
Create Date: 2026-01-19 21:34:08.334772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed28f44c90ec'
down_revision: Union[str, Sequence[str], None] = 'bbed1e384a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('likes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'likes')
    # ### end Alembic commands ###
