"""database table generation

Revision ID: f0ed73a30185
Revises: a3b2a34fe886
Create Date: 2026-02-01 19:07:49.096266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0ed73a30185'
down_revision: Union[str, Sequence[str], None] = 'a3b2a34fe886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='images_pk')
    )
    op.create_index('idx_image_image_url', 'images', ['image_url'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='roles_pk'),
    sa.UniqueConstraint('name', name='name_unique_key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('nationality', sa.VARCHAR(length=50), nullable=False),
    sa.Column('hash_password', sa.Text(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='role_id_fk', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='users_pk'),
    sa.UniqueConstraint('email', name='email_unique_key'),
    sa.UniqueConstraint('username', name='username_unique_key')
    )
    op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_display_name', 'users', ['display_name'], unique=False, postgresql_using='gin', postgresql_ops={'display_name': 'gin_trgm_ops'})
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_nationality', 'users', ['nationality'], unique=False)
    op.create_index('idx_user_role_id', 'users', ['role_id'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False, postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.create_table('follows',
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='follower_id_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name='following_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('following_id', 'follower_id', name='follows_pk')
    )
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', 'content')", persisted=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'FOLLOWERS', 'PRIVATE', name='visibilityenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='posts_pk')
    )
    op.create_index('idx_post_content_search', 'posts', ['content_search'], unique=False, postgresql_using='gin')
    op.create_index('idx_post_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('idx_post_title', 'posts', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('idx_post_user_id', 'posts', ['user_id'], unique=False)
    op.create_table('profile_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name='image_id_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='profile_images_pk')
    )
    op.create_index('idx_profile_image_image_id', 'profile_images', ['image_id'], unique=False)
    op.create_index('idx_profile_image_user_id', 'profile_images', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'REVOKED', 'USED', name='tokenstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pk')
    )
    op.create_index('idx_auth_token', 'refresh_tokens', ['token'], unique=False)
    op.create_index('idx_auth_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_id_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='comments_pk')
    )
    op.create_index('idx_comment_created_at', 'comments', ['created_at'], unique=False)
    op.create_index('idx_comment_post_id', 'comments', ['post_id'], unique=False)
    op.create_index('idx_comment_user_id', 'comments', ['user_id'], unique=False)
    op.create_table('likes',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('liked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id', name='likes_pk')
    )
    op.create_index('idx_like_post_id', 'likes', ['post_id'], unique=False)
    op.create_index('idx_like_user_id', 'likes', ['user_id'], unique=False)
    op.create_table('post_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name='image_id_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='post_images_pk')
    )
    op.create_index('idx_post_image_image_id', 'post_images', ['image_id'], unique=False)
    op.create_index('idx_post_image_user_id', 'post_images', ['post_id'], unique=False)
    op.create_table('comment_likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('liked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='comment_id_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id', name='comment_likes_pk')
    )
    op.create_index('idx_comment_like_comment_id', 'comment_likes', ['comment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_comment_like_comment_id', table_name='comment_likes')
    op.drop_table('comment_likes')
    op.drop_index('idx_post_image_user_id', table_name='post_images')
    op.drop_index('idx_post_image_image_id', table_name='post_images')
    op.drop_table('post_images')
    op.drop_index('idx_like_user_id', table_name='likes')
    op.drop_index('idx_like_post_id', table_name='likes')
    op.drop_table('likes')
    op.drop_index('idx_comment_user_id', table_name='comments')
    op.drop_index('idx_comment_post_id', table_name='comments')
    op.drop_index('idx_comment_created_at', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_auth_user_id', table_name='refresh_tokens')
    op.drop_index('idx_auth_token', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_profile_image_user_id', table_name='profile_images')
    op.drop_index('idx_profile_image_image_id', table_name='profile_images')
    op.drop_table('profile_images')
    op.drop_index('idx_post_user_id', table_name='posts')
    op.drop_index('idx_post_title', table_name='posts', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_post_created_at', table_name='posts')
    op.drop_index('idx_post_content_search', table_name='posts', postgresql_using='gin')
    op.drop_table('posts')
    op.drop_table('follows')
    op.drop_index('idx_user_username', table_name='users', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.drop_index('idx_user_role_id', table_name='users')
    op.drop_index('idx_user_nationality', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_display_name', table_name='users', postgresql_using='gin', postgresql_ops={'display_name': 'gin_trgm_ops'})
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index('idx_image_image_url', table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
